package com.plumre.dao;

import com.plumre.dataobject.ItemDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue Mar 26 10:44:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue Mar 26 10:44:03 CST 2019
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue Mar 26 10:44:03 CST 2019
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue Mar 26 10:44:03 CST 2019
     */
    ItemDO selectByPrimaryKey(Integer id);


    List<ItemDO> listItems();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue Mar 26 10:44:03 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue Mar 26 10:44:03 CST 2019
     */
    int updateByPrimaryKey(ItemDO record);

    void updateSales(@Param("id") Integer id, @Param("quantity") Integer quantity);
}